### ISSUE TITLE
Type definition in fastdownward_simple.pddl

### ISSUE THREAD

**Issue by FlorianPommerening** [dtdannen/dcss-ai-wrapper#19]
During the ICAPS tutorial, we noticed some strange behavior when trying to go down the stairs. I think I traced this back to an issue in the domain PDDL file. The type section there starts like this
```
(:types monster
        cell
        ...
        non_target_based_spell - spell
 )
```

I think the semantics of types `A B C - D` is that `D` is a super type of `A`, `B`, and `C`, so in this case, all types mentioned before `non_target_based_spell` have the supertype `spell` which is not their intended meaning. 

I'm attaching two files that contain a minimal example of the problematic case (had to rename them to txt for Github).
[domain.pddl.txt](https://github.com/dtdannen/dcss-ai-wrapper/files/6925178/domain.pddl.txt)
[problem.pddl.txt](https://github.com/dtdannen/dcss-ai-wrapper/files/6925180/problem.pddl.txt)
With the files like this, Fast Downward will not find a plan, but after removing line 8 (`equipitem - item`) from the domain, it does.

The fix should be to use the supertype `object` for all types without a supertype (`object` is a reserved word in PDDL for the default type). I tried this but then got another error from the Fast Downward translator (something about an impossible condition). My guess is that this is a new error that was hidden by the incorrect types so far.

**Comment by dtdannen** [comment]
Solved the PDDL file errors so planning example works, Still need to confirm that issue is fixed completely and the agent is able to traverse to the stairs when given a goal to reach the next level.

Used the web editor at planning.domains to debug the pddl files, which was extremely helpful at providing hints to where the problems were.

One of the problems was that not all actions had types given for the arguments. There were also some other typos that are now fixed.
